#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

if [[ -z "$PLUSHU_BUILDPACKS_DIR" ]]; then
  echo "No buildpacks dir defined; aborting." >&2
  exit 1
fi

i=`ls -f "$PLUSHU_BUILDPACKS_DIR" | wc -l`

for buildpack in oortcloud/heroku-buildpack-meteorite \
  miyagawa/heroku-buildpack-perl igrigorik/heroku-buildpack-dart \
  rhy-jot/buildpack-nginx Kloadut/heroku-buildpack-static-apache \
  bacongobbler/heroku-buildpack-jekyll
do
  "$PLUSHU_ROOT/lib/plushook" install-buildpack $(printf '%02i_%s' \
    "$i" "${buildpack##*/}") "https://github.com/$buildpack.git"
  i=$((i+1))
done

